"""add layout template to export job

Revision ID: b10d1c777b0a
Revises: 7e43a47327ec
Create Date: 2026-10-08 11:05:48.100810

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 3.2 (ADR-0030, technical plan §0.12 and §5): a PDF export records the layout it was rendered
in. One nullable column on `export_job`, a back-fill, and a paired CHECK. The reasons for the column
and the constraint are on the `Table` in `infrastructure/persistence/mapping/export/export_job.py`
once T12 lands; this revision lands **before** that mapping, because a mapped column the table lacks
breaks every load (2.3's lesson).

**Expand-only, for this deploy.** `deploy.yml` stops `worker`/`beat`, starts the new `api`, and only
then runs `alembic upgrade head`; the old code never writes against the new schema. Every PDF row the
old code wrote exists before this runs, and the back-fill gives each one `'classic'` — the only look
1.5 to 3.1 could render — so the CHECK added after it holds on every existing row.

**The CHECK pairs the column with the format**: a PDF row has a layout, a DOCX row has none. Written
as an equality of two booleans so both directions are one predicate. **No value CHECK on the three
ids** (plan §0.12): `status` and `failure_reason` carry none either, the `TypeDecorator` is the
authority, and a value CHECK would make a fourth layout a migration.

**One revision, plain `ADD CONSTRAINT`**, not `NOT VALID` → `VALIDATE`: inside one revision the split
releases no lock (CLAUDE.md footgun). At production's row count the `ACCESS EXCLUSIVE` lasts
milliseconds; T28 reads that count and splits the revision if it exceeds ~100 k rows.

**Downgrade refuses while any row has a layout other than `'classic'`** — 2.2/2.3/3.1's stance (refuse
when a downgrade would make data mean something else). 1.5's code keys idempotency without the layout,
so it would hand a Formal file to a request that, in 1.5, can only mean the one look. On Classic-only
data it drops the constraint, then the column (one dropped-column slot, PR #12).

**Reviewed line by line.** The draft was empty (`pass` in both functions): the mapping does not carry
the column yet (T12), so autogenerate had nothing to diff — correct, and nothing invented. Everything
below is hand-written, names wrapped in `op.f()` so no naming convention is applied on top.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op

revision: str = "b10d1c777b0a"
down_revision: str | None = "7e43a47327ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CHECK_NAME = "ck_export_job_layout_template_only_for_pdf"
_NON_CLASSIC_SQL = "FROM export_job WHERE layout_template <> 'classic'"
_REFUSAL = (
    "refusing to downgrade b10d1c777b0a: export_job holds {count} job(s) rendered in a layout other "
    "than classic, and the previous schema keys an export without its layout, so those rows would "
    "be handed to requests that mean the classic look. Delete those jobs first, or do not "
    "downgrade — this migration never deletes data to make a downgrade fit."
)


def upgrade() -> None:
    # `LayoutTemplateType.impl` (T12). Nullable: a DOCX job has no layout (the CHECK below).
    op.add_column("export_job", sa.Column("layout_template", sa.String(length=32), nullable=True))
    # Every PDF the old code rendered was the one look 3.2 calls Classic.
    op.execute("UPDATE export_job SET layout_template = 'classic' WHERE format = 'pdf'")
    op.create_check_constraint(
        op.f(_CHECK_NAME),
        "export_job",
        "(format = 'pdf') = (layout_template IS NOT NULL)",
    )


def downgrade() -> None:
    # Taken before the look, so no non-classic job can be inserted between the count and the
    # `DROP COLUMN` (which needs `ACCESS EXCLUSIVE` anyway).
    op.execute("LOCK TABLE export_job IN ACCESS EXCLUSIVE MODE")
    if context.is_offline_mode():
        # A generated script has no connection to ask, so the refusal travels in the SQL itself.
        # Interpolates only this module's constants, none of which holds a quote.
        op.execute(
            f"DO $$ BEGIN IF EXISTS (SELECT 1 {_NON_CLASSIC_SQL}) "
            f"THEN RAISE EXCEPTION '{_REFUSAL.format(count='some')}'; END IF; END $$"
        )
    else:
        count = op.get_bind().execute(sa.text(f"SELECT count(*) {_NON_CLASSIC_SQL}")).scalar_one()
        if count:
            raise RuntimeError(_REFUSAL.format(count=count))

    op.drop_constraint(op.f(_CHECK_NAME), "export_job", type_="check")
    op.drop_column("export_job", "layout_template")
