"""add base cv and guest session

Revision ID: 3a39cf023a18
Revises:
Create Date: 2026-09-08 10:27:36.076955

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

This is the project's first revision (`down_revision = None`), so there is nothing to expand from or
contract into — both tables are wholly new.

Hand-fixed after autogenerate (ADR-0007 "autogenerate is a draft, read every line"): every
`TypeDecorator` column (`GuestSessionIdType`, `BaseCvIdType`, `OriginalFilenameType`,
`CvContentTypeType`, `FileRefType`, `BaseCvStatusType`, `ExtractionFailureReasonType`,
`ExtractedTextType`) came out of `alembic revision --autogenerate` as a bare reference to the
Python class — `tailorcraft.infrastructure.persistence.types.identity.GuestSessionIdType()` — with
no `import tailorcraft` anywhere in the file. That is not a rendering nicety to clean up; the
generated module raises `NameError` the moment Alembic tries to `exec` it. Every such column below
is rewritten to the `TypeDecorator`'s own `impl` — the column's actual wire type in Postgres — which
is also the right thing structurally: a migration should describe the *schema*, not import the ORM
layer that happens to produce it today. `TIMESTAMP(timezone=True, precision=0)` and the check/unique/
foreign-key/index definitions needed no such fix — they came out of autogenerate correct, because
`base_cv_table` / `guest_session_table` declare those directly rather than through a `TypeDecorator`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3a39cf023a18"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "identity_guest_session",
        # `GuestSessionIdType.impl` — a native Postgres UUID.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_guest_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_identity_guest_session_token_hash")),
    )
    op.create_index(
        op.f("ix_identity_guest_session_expires_at"),
        "identity_guest_session",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "intake_base_cv",
        # `BaseCvIdType.impl` — a native Postgres UUID.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `GuestSessionIdType.impl`, same as `identity_guest_session.id` above.
        sa.Column("guest_session_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `OriginalFilenameType.impl`.
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        # `CvContentTypeType.impl` — the sniffed MIME type.
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        # `FileRefType.impl`.
        sa.Column("file_key", sa.String(length=512), nullable=False),
        # `BaseCvStatusType.impl` — plain `String`, deliberately not a native enum (ADR-0007:
        # adding a member to a Postgres `ENUM` takes a lock, and this set is expected to grow).
        sa.Column("status", sa.String(length=32), nullable=False),
        # `ExtractedTextType.impl` — nullable until extraction is decided (I-2).
        sa.Column("extracted_text", sa.Text(), nullable=True),
        # `ExtractionFailureReasonType.impl`, same "plain String, not a native enum" reasoning as
        # `status` above.
        sa.Column("extraction_failure_reason", sa.String(length=64), nullable=True),
        sa.Column("uploaded_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("extracted_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_intake_base_cv_size_bytes_positive")),
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["identity_guest_session.id"],
            name=op.f("fk_intake_base_cv_guest_session_id_identity_guest_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_base_cv")),
        sa.UniqueConstraint("file_key", name=op.f("uq_intake_base_cv_file_key")),
    )
    op.create_index(
        op.f("ix_intake_base_cv_guest_session_id"),
        "intake_base_cv",
        ["guest_session_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_intake_base_cv_guest_session_id"), table_name="intake_base_cv")
    op.drop_table("intake_base_cv")
    op.drop_index(op.f("ix_identity_guest_session_expires_at"), table_name="identity_guest_session")
    op.drop_table("identity_guest_session")
