"""add pending registration and password reset

Revision ID: b1b518fe84b1
Revises: 03494836ce30
Create Date: 2026-10-02 11:46:25.547790

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 2.5 (ADR-0027, ADR-0028, technical plan §5): two new tables for the one-time tokens a mailed
link carries — a sign-up awaiting confirmation and a password reset — and one index on the existing
`identity_login`, for the identity token sweep. The reasons for every column and constraint are on the
`Table`s in `infrastructure/persistence/mapping/identity/pending_registration.py`, `password_reset.py`
and `login.py`, which is what ships; take the authoritative text from there.

**Expand-only.** Two tables nothing has ever written and one index; no existing column or constraint
is created, altered or dropped. The previous application version does not know the tables exist and
never reads `ix_identity_login_expires_at`, so the two-version deploy window is safe by construction.

**No foreign key references `identity_guest_session`.** The one foreign key added,
`identity_password_reset.user_id` → `identity_user.id`, is `ON DELETE CASCADE`, so an erased account
takes its issued resets with it; its *addressed* resets and pending registrations are deleted by
address by the erasure itself (`SqlAlchemyAccountData.delete_account`).

**Credential-shaped columns**: `identity_pending_registration.password_hash` (a PHC string) and the
two `CHAR(64)` token hashes. No plaintext password or token has a column anywhere.

**Plain `CREATE INDEX`, not `CONCURRENTLY`.** Five of the six indexes are on tables created earlier in
the same transaction. The sixth, `ix_identity_login_expires_at`, is on a live table and holds its
write lock until this revision commits (Alembic runs a revision in one transaction); production's
`identity_login` holds the canary's few rows (T46), so that is milliseconds. CLAUDE.md's "split the
revision if the table grows" applies to it and is not triggered.

**Downgrade drops the index and both tables and refuses nothing** — the deliberate contrast with
`1a2676aa3759` and `03494836ce30`, whose downgrades refuse because they would lose *kept* data. These
rows are one-time tokens living at most 24 hours; a lost pending registration costs its owner one
re-registration and a lost reset one more request; and a rollback must never be blocked by a
stranger's half-finished sign-up. After a downgrade to 2.4's code, registration enumerates again —
ADR-0008 (b)'s state, consistent with that code. Tables are dropped, never columns, so it consumes no
dropped-column slots (PR #12).

**Reviewed line by line.** `render_item` rendered every `TypeDecorator` column as its `impl` —
`postgresql.UUID(as_uuid=True)` for the three ids, `sa.String(254)` for both emails (`EmailAddressType`,
`identity_user.email`'s type: plan §5 wrote `text`, and reusing the type keeps the two comparable like
with like), `sa.String(512)` for the password hash, `sa.CHAR(64)` for both token hashes — and every
instant as `postgresql.TIMESTAMP(timezone=True, precision=0)`. Every name is the one plan §5 lists,
wrapped in `op.f()` so no naming convention is applied on top of it. Nothing invented: no drop, no
alteration of an existing object. Changed from the draft: rewrapped for `ruff format`, the
autogenerate marker comments removed, comments added; the file renamed from its truncated slug.

Verified against the dev database (at `03494836ce30`): `alembic upgrade head`, `alembic downgrade -1`,
`alembic upgrade head`; and against `tailorcraft_test` the same round trip. From empty, the test
suite's `_migrated` fixture runs the whole chain on every session.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b1b518fe84b1"
down_revision: str | None = "03494836ce30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "identity_pending_registration",
        # `PendingRegistrationIdType.impl`. Application-assigned UUIDv7 (ADR-0007): no default.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `EmailAddressType.impl`; the UNIQUE below is `put`'s conflict target (one per address).
        sa.Column("email", sa.String(length=254), nullable=False),
        # `PasswordHashType.impl` — a PHC string, never a plaintext.
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("requested_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        # `TokenHashType.impl`, NULL until the worker issues the link.
        sa.Column("token_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("issued_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        sa.CheckConstraint(
            "(token_hash IS NULL) = (issued_at IS NULL)",
            name=op.f("ck_identity_pending_registration_issued_together"),
        ),
        sa.CheckConstraint(
            "expires_at > requested_at",
            name=op.f("ck_identity_pending_registration_expires_after_request"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_pending_registration")),
        sa.UniqueConstraint("email", name=op.f("uq_identity_pending_registration_email")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_identity_pending_registration_token_hash")),
    )
    op.create_index(
        op.f("ix_identity_pending_registration_expires_at"),
        "identity_pending_registration",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "identity_password_reset",
        # `PasswordResetIdType.impl` / `EmailAddressType.impl` / `UserIdType.impl`.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # The two halves of `ResetTarget`: the address while requested, the account once issued.
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("token_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("requested_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("issued_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        sa.CheckConstraint(
            "(email IS NULL) <> (user_id IS NULL)",
            name=op.f("ck_identity_password_reset_exactly_one_target"),
        ),
        sa.CheckConstraint(
            "(user_id IS NULL) = (token_hash IS NULL) AND (token_hash IS NULL) = (issued_at IS NULL)",
            name=op.f("ck_identity_password_reset_issued_with_account"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_user.id"],
            name=op.f("fk_identity_password_reset_user_id_identity_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_password_reset")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_identity_password_reset_token_hash")),
    )
    op.create_index(
        op.f("ix_identity_password_reset_email"),
        "identity_password_reset",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_password_reset_expires_at"),
        "identity_password_reset",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_password_reset_user_id"),
        "identity_password_reset",
        ["user_id"],
        unique=False,
    )
    # On the existing, live table — the one statement here that locks something already in use.
    op.create_index(
        op.f("ix_identity_login_expires_at"), "identity_login", ["expires_at"], unique=False
    )


def downgrade() -> None:
    # Refuses nothing, on purpose — the module docstring says why. Reverse order of `upgrade`.
    op.drop_index(op.f("ix_identity_login_expires_at"), table_name="identity_login")
    op.drop_index(op.f("ix_identity_password_reset_user_id"), table_name="identity_password_reset")
    op.drop_index(
        op.f("ix_identity_password_reset_expires_at"), table_name="identity_password_reset"
    )
    op.drop_index(op.f("ix_identity_password_reset_email"), table_name="identity_password_reset")
    op.drop_table("identity_password_reset")
    op.drop_index(
        op.f("ix_identity_pending_registration_expires_at"),
        table_name="identity_pending_registration",
    )
    op.drop_table("identity_pending_registration")
