"""add user owner to posting, run and export

Revision ID: 03494836ce30
Revises: 1a2676aa3759
Create Date: 2026-09-28 16:37:14.075908

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 2.3 (ADR-0023, technical plan §5, AC-16): a job posting, a tailoring run and an export job can
be owned by a guest session **or** a user — `intake_base_cv`'s 2.2 shape (ADR-0022, revision
`1a2676aa3759`) applied to three more tables. A product of two nullable owner columns, and a CHECK
per table restoring "exactly one". The reasons for every column, index and constraint are on the
`Table`s in `infrastructure/persistence/mapping/{posting,tailoring,export}/`, which is what ships;
this docstring is what a reader of *this* file needs.

**Expand-only, and backward-compatible with the running 2.2 code (AC-17).** 2.2 inserts only guest
rows — no `user_id`, a non-null `guest_session_id` — which every new constraint accepts; it reads a
run, posting or job by id or by `guest_session_id`, and a user-owned row has `guest_session_id IS
NULL`, so on a 2.2 route it is a 404; its purge and orphan sweep are owner-blind in exactly the safe
directions (the cascade cannot reach a row with `guest_session_id IS NULL`, and the cross-check reads
`file_key` for every row). Nothing is renamed, retyped or dropped. `tailoring_run.failure_reason`
gains the value `base_cv_deleted` with no DDL: it is a `VARCHAR` and no CHECK lists its values.

**The order is the point** (technical plan §5), the same for each table:

  1. Add `user_id`, nullable and without a default — a catalog-only change, no rewrite.
  2. Its foreign key `NOT VALID`, then `VALIDATE CONSTRAINT`. `NOT VALID` takes the brief lock and
     enforces the FK on new writes at once; `VALIDATE` scans under `SHARE UPDATE EXCLUSIVE`, which
     blocks neither reads nor writes. The column is all-NULL, so the scan finds nothing to check.
  3. The index. Plain `CREATE INDEX`, not `CONCURRENTLY`: Alembic runs a revision in one
     transaction, which `CONCURRENTLY` refuses, and the build is milliseconds at today's row counts.
     It blocks writes to its table while it builds. T38 reads production's row counts first; above
     ~100 k rows in any of the three tables, the index moves to its own non-transactional revision.
  4. The CHECK `NOT VALID`, then `VALIDATE CONSTRAINT` — every existing row has exactly one owner,
     its guest session, so validation passes.
  5. `DROP NOT NULL` on `guest_session_id` **last**. Until this line runs the old `NOT NULL` still
     refuses an ownerless row; from this line on the CHECK does. There is no instant at which a row
     with no owner is permitted.

**The downgrade refuses** while any of the three tables holds a user-owned row, or any run has
failed `base_cv_deleted`, raising a sentence instead of deleting data. A user-owned row cannot be
represented once `guest_session_id` is `NOT NULL` again, and restoring it would fail half-way on the
first one — at which point the "fix" someone would reach for is a `DELETE` of registered users'
history. A `base_cv_deleted` run can be represented, but 2.2's enum has no such member, so 2.2 would
raise on loading it. With neither present, every row is a guest row 2.2 can read, and dropping
`user_id` loses nothing.

**Reviewed line by line against the autogenerate draft** (Alembic 1.19.1, SQLAlchemy 2.0.52).
`render_item` had already rendered every `TypeDecorator` as its `impl` (`postgresql.UUID(as_uuid=True)`
for each `user_id`), so there was no decorator reference to replace. Every constraint and index name
matches plan §5 and `registry.py`'s convention, wrapped in `op.f()` so no convention is applied on
top. Changed from the draft:

  1. **The draft ran `alter_column(nullable=True)` first on each table**, before its CHECK existed —
     for the length of the revision nothing refused an ownerless row. Moved to the end of each
     table's block (step 5).
  2. **The draft created each FK and each CHECK validated inline.** Now `postgresql_not_valid=True`
     plus an explicit `VALIDATE CONSTRAINT` each (steps 2 and 4).
  3. **The draft rendered the two composite indexes faithfully — contrary to plan §5's expectation**
     — as `sa.literal_column('created_at DESC')`, which compiles to `(user_id, created_at DESC, id
     DESC)` exactly (checked with `--sql`, and read back from `pg_indexes.indexdef` after the
     upgrade). They are rewritten as `sa.text(...)`,
     the form the mapping uses, and their names wrapped in `op.f()` like every other name here. The
     draft's log line described them as `on ('user_id',)`; the operation itself was right.
  4. **The draft's downgrade restored `NOT NULL` unconditionally.** It now locks the three tables and
     refuses first (above); then drops each CHECK, index and FK before the column they name.
  5. Reordered table by table (posting, run, export — the draft went export first), rewrapped for
     `ruff format`, the autogenerate marker comments removed, comments added.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Final

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

revision: str = "03494836ce30"
down_revision: str | None = "1a2676aa3759"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The three tables in the order this revision touches them. `(table, index name, index columns)`.
# Index columns are `text()` so the two composite indexes carry their `DESC` exactly as the mapping
# declares them; `export_job`'s is a plain single-column index (nothing lists a user's jobs in order).
# No refusal sentence below may contain a single quote: offline, each travels inside a SQL literal.
_TABLES: Final[tuple[tuple[str, str, tuple[str, ...]], ...]] = (
    (
        "posting_job_posting",
        "ix_posting_job_posting_user_id_created_at",
        ("user_id", "created_at DESC", "id DESC"),
    ),
    (
        "tailoring_run",
        "ix_tailoring_run_user_id_requested_at",
        ("user_id", "requested_at DESC", "id DESC"),
    ),
    ("export_job", "ix_export_job_user_id", ("user_id",)),
)

_REFUSAL_USER_OWNED = (
    "refusing to downgrade 03494836ce30: {table} holds rows owned by registered users, and the "
    "previous schema cannot represent them (guest_session_id NOT NULL). Erase those accounts first "
    "(python -m tailorcraft.cli erase-account), or do not downgrade — this migration never deletes "
    "data to make a downgrade fit."
)
_REFUSAL_BASE_CV_DELETED = (
    "refusing to downgrade 03494836ce30: tailoring_run holds runs that failed with "
    "base_cv_deleted, a reason the previous release cannot load. Those runs are user-owned "
    "history; erase their accounts first, or do not downgrade — this migration never deletes data "
    "to make a downgrade fit."
)


def upgrade() -> None:
    for table, index_name, index_columns in _TABLES:
        # 1. The column. Nullable, no default: no table rewrite. `UserIdType.impl`.
        op.add_column(table, sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True))

        # 2. The FK: enforced on new writes at once, the (empty) existing column validated after.
        fk_name = f"fk_{table}_user_id_identity_user"
        op.create_foreign_key(
            op.f(fk_name),
            table,
            "identity_user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
            postgresql_not_valid=True,
        )
        op.execute(f"ALTER TABLE {table} VALIDATE CONSTRAINT {fk_name}")

        # 3. The index.
        op.create_index(
            op.f(index_name),
            table,
            [sa.text(column) for column in index_columns],
            unique=False,
        )

        # 4. The CHECK: enforced on new writes at once, existing rows validated separately.
        ck_name = f"ck_{table}_exactly_one_owner"
        op.create_check_constraint(
            op.f(ck_name),
            table,
            "num_nonnulls(guest_session_id, user_id) = 1",
            postgresql_not_valid=True,
        )
        op.execute(f"ALTER TABLE {table} VALIDATE CONSTRAINT {ck_name}")

        # 5. Last: from here on the CHECK, not `NOT NULL`, refuses an ownerless row.
        op.alter_column(table, "guest_session_id", existing_type=sa.UUID(), nullable=True)


def _refuse_if_present(condition_sql: str, refusal: str) -> None:
    """Raise `refusal` if `SELECT 1 … WHERE condition` finds a row — in SQL when offline."""
    if context.is_offline_mode():
        # A generated script has no connection to ask, so the refusal travels in the SQL itself.
        # Interpolates only this module's constants, none of which holds a quote.
        op.execute(
            f"DO $$ BEGIN IF EXISTS ({condition_sql}) "
            f"THEN RAISE EXCEPTION '{refusal}'; END IF; END $$"
        )
    elif op.get_bind().execute(sa.text(f"SELECT EXISTS ({condition_sql})")).scalar_one():
        raise RuntimeError(refusal)


def downgrade() -> None:
    # Taken before the look, so no user-owned row can be inserted between the check and the `SET NOT
    # NULL` below. Every `ALTER TABLE` that follows needs `ACCESS EXCLUSIVE` anyway.
    for table, _, _ in _TABLES:
        op.execute(f"LOCK TABLE {table} IN ACCESS EXCLUSIVE MODE")

    for table, _, _ in _TABLES:
        _refuse_if_present(
            f"SELECT 1 FROM {table} WHERE user_id IS NOT NULL",  # noqa: S608 -- `table` is a module constant; no input reaches this string
            _REFUSAL_USER_OWNED.format(table=table),
        )
    _refuse_if_present(
        "SELECT 1 FROM tailoring_run WHERE failure_reason = 'base_cv_deleted'",
        _REFUSAL_BASE_CV_DELETED,
    )

    for table, index_name, _ in reversed(_TABLES):
        # Constraints and the index before the column they name.
        op.drop_constraint(op.f(f"ck_{table}_exactly_one_owner"), table, type_="check")
        op.drop_index(op.f(index_name), table_name=table)
        op.drop_constraint(op.f(f"fk_{table}_user_id_identity_user"), table, type_="foreignkey")
        # Safe now: no user-owned row, and the CHECK guaranteed every other row a guest owner.
        op.alter_column(table, "guest_session_id", existing_type=sa.UUID(), nullable=False)
        op.drop_column(table, "user_id")
