"""index running tailoring runs

Revision ID: 3d0b70b7837f
Revises: 33d8cf628221
Create Date: 2026-09-13 09:28:31.534473

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

One partial index, `ix_tailoring_run_running_started_at ON tailoring_run (started_at) WHERE status =
'running'`. It serves `SqlAlchemyTailoringRunRepository.list_stale_running`, the stale-run sweep that
Celery beat runs every minute (G-25', verify round 1). The reasons for a *partial* index, for
`started_at` alone, and for the name are on the `Index` in
`infrastructure/persistence/mapping/tailoring/tailoring_run.py`, which is what ships. Take the
authoritative text from there.

Purely additive: nothing existing is altered or dropped. The previous application version never
issues the query this serves and is indifferent to the index, so the brief two-version deploy
window is safe.

**Reviewed line by line, and this time the draft had no `TypeDecorator` failure.** The first three
revisions each had to be hand-fixed for the same fault, a `TypeDecorator` column rendered as an
unimportable class reference. The risk here was that fault turning up *inside the partial
predicate*. It did not, because the `Index` declares its predicate as `text("status = 'running'")`,
the same way the table's CHECKs are declared, not as an expression over the decorated `status`
column. Autogenerate copies a `text()` verbatim.

Changed from the draft:
  - `op.f()` around the name, as the earlier revisions use: it marks the name as final, so no naming
    convention is ever applied on top of it;
  - `postgresql_where` removed from `drop_index`. `DROP INDEX` takes no predicate, so the argument
    only suggested one mattered there;
  - rewrapped for `ruff format`, and comments added.

**A plain `CREATE INDEX`, not `CREATE INDEX CONCURRENTLY`, and this is a decision with an expiry.**
A plain build holds a `SHARE` lock on `tailoring_run` for its duration, so writes to the table wait.
A partial index is small, but building it still scans the **whole heap**, so the wait grows with the
table, not with the index. Today that is nothing: this migration ships in the same release as the
table's first production rows, so it is building over an empty table. `CONCURRENTLY` would cost an
`autocommit_block()` and a failure mode of its own, an `INVALID` index left behind to find and drop
by hand, to protect writes on a table with no rows. **The next index on `tailoring_run` meets a table
that is live and growing, and should be built `CONCURRENTLY`.**

Verified against the dev database, which started at 33d8cf628221: `alembic upgrade head`, then
`alembic downgrade -1` (index gone), then `alembic upgrade head` again (index back, exactly as
declared).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3d0b70b7837f"
down_revision: str | None = "33d8cf628221"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The predicate must stay textually `status = 'running'`, the value `TailoringRunStatusType`
    # stores for `TailoringRunStatus.RUNNING`. The repository renders the status as a literal for
    # the same reason the index is partial: the planner uses a partial index only when it can prove
    # the query's `WHERE` implies this one.
    op.create_index(
        op.f("ix_tailoring_run_running_started_at"),
        "tailoring_run",
        ["started_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_tailoring_run_running_started_at"), table_name="tailoring_run")
