"""add tailoring run revision and version

Revision ID: 274e4abc5d73
Revises: 3d0b70b7837f
Create Date: 2026-09-13 16:58:19.026130

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 1.4 (ADR-0015): five columns and three CHECK constraints on `tailoring_run`, and nothing else.

- `version INTEGER NOT NULL DEFAULT 1` — the optimistic-concurrency counter the mapping declares as
  `version_id_col` with `version_id_generator=False` (ADR-0015 §3, invariant TR-8). The aggregate
  owns the number: `request()` sets 1 and every transition bumps it; the mapper only *checks*.
- `edited_cv TEXT NULL` and `edited_cover_letter TEXT NULL` — the user's revision of each document,
  beside (never over) the model's draft in `tailored_cv` / `cover_letter` (TR-11). **Both are
  PII**, exactly as the two draft columns are. They reuse `TailoredCvType` and `CoverLetterType`, so
  the draft and the revision can never be validated by different rules.
- `cv_edited_at` and `cover_letter_edited_at`, `TIMESTAMP(0) WITH TIME ZONE NULL` — whole-second,
  per the `Clock` contract, declared exactly as the three 1.3 instants are.
- Three CHECKs: the two pairing constraints (TR-10 — a revision and its instant are set together or
  not at all, an equality between two predicates so each rejects both bad pairings), and
  `revision_requires_success` (TR-9 — a revision exists only on a `succeeded` row, an implication
  and not an equality because a succeeded run with no revision is the normal state of every run the
  user never edited). The reasons are on the `CheckConstraint`s in
  `infrastructure/persistence/mapping/tailoring/tailoring_run.py`, which is what ships; take the
  authoritative text from there.

**Expand only, and the `DEFAULT 1` stays.** Purely additive: nothing existing is altered or
dropped, 1.3's three CHECKs are untouched (they speak about the draft columns, which this slice
never writes), and `ix_tailoring_run_running_started_at` is untouched. The previous application
version never reads the five columns and its `UPDATE`s never touch `version`, so the two-version
deploy window is safe — and its `INSERT`s, which know nothing of `version`, get the `DEFAULT 1`.
That default is *for* the deploy window and hand-written `INSERT`s, not for the application, which
is why there is no contract step to drop it. PostgreSQL 11+ adds a constant, non-volatile default
without rewriting the table (the value is stored in `pg_attribute.attmissingval` and applied on
read), so the `ALTER TABLE … ADD COLUMN … NOT NULL DEFAULT 1` is instant on a live table.

**Reviewed line by line, and for the first time in five revisions the draft needed no hand-fix of a
type (AC-1).** The first three revisions each rendered every `TypeDecorator` column as an
unimportable class reference and were fixed by hand; the fourth had no decorated column. This is
the first draft *with* decorated columns (`edited_cv`, `edited_cover_letter`) that rendered them as
their `impl` — `sa.Text()` — because `alembic/env.py` now carries the `render_item` hook that
rewrites a decorator as its wire type. `sa.Integer()` with `server_default=sa.text("1")` and
`postgresql.TIMESTAMP(timezone=True, precision=0)` came out correct as they always have. The draft
proposed no drop of the partial index and no change to any existing column or constraint.

Changed from the draft: rewrapped for `ruff format` (double quotes, one argument per line), the
autogenerate marker comments removed, and comments added. Nothing else.

Verified against the dev database, which started at 3d0b70b7837f: `alembic upgrade head` (five
columns and three CHECKs present, the partial index and 1.3's three CHECKs unchanged), then
`alembic downgrade 3d0b70b7837f` (all eight gone, `alembic_version` back at 3d0b70b7837f, the
partial index still there), then `alembic upgrade head` again (all eight back, exactly as
declared). `alembic check` then reported no new upgrade operations, so the mapping and the migrated
schema agree.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "274e4abc5d73"
down_revision: str | None = "3d0b70b7837f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `NOT NULL DEFAULT 1` in one statement: the default is what lets the column be added `NOT NULL`
    # to a table that already has rows, and what the previous application version's `INSERT`s rely
    # on during the deploy window. It stays after the deploy (module docstring).
    op.add_column(
        "tailoring_run",
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    # `TailoredCvType.impl` and `CoverLetterType.impl` — TEXT, the same wire type as the two draft
    # columns, rendered as such by `render_item` rather than fixed by hand. PII, both.
    op.add_column("tailoring_run", sa.Column("edited_cv", sa.Text(), nullable=True))
    op.add_column("tailoring_run", sa.Column("edited_cover_letter", sa.Text(), nullable=True))
    # Whole-second by contract (ADR-0007), as `requested_at`, `started_at` and `completed_at` are.
    op.add_column(
        "tailoring_run",
        sa.Column("cv_edited_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
    )
    op.add_column(
        "tailoring_run",
        sa.Column(
            "cover_letter_edited_at",
            postgresql.TIMESTAMP(timezone=True, precision=0),
            nullable=True,
        ),
    )
    # TR-10 where Python cannot reach: `revise_cv` / `revise_cover_letter` write the revision and
    # its instant in one statement, and a hand-written `UPDATE` need not. An equality between two
    # predicates, so one expression rejects both a revision without its instant and an instant
    # without its revision.
    op.create_check_constraint(
        op.f("ck_tailoring_run_cover_letter_revision_pairs"),
        "tailoring_run",
        "(edited_cover_letter IS NULL) = (cover_letter_edited_at IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_tailoring_run_cv_revision_pairs"),
        "tailoring_run",
        "(edited_cv IS NULL) = (cv_edited_at IS NULL)",
    )
    # TR-9: a revision is legal only from `succeeded`. An implication, not an equality — a succeeded
    # run with no revision is the normal state of every run the user never edited.
    op.create_check_constraint(
        op.f("ck_tailoring_run_revision_requires_success"),
        "tailoring_run",
        "(edited_cv IS NULL AND edited_cover_letter IS NULL) OR status = 'succeeded'",
    )


def downgrade() -> None:
    # Constraints first, then the columns they reference. All three CHECKs span more than one
    # column, and PostgreSQL refuses to drop a column a multi-column constraint still names unless
    # told `CASCADE` — which `op.drop_column` does not say, and should not.
    op.drop_constraint(
        op.f("ck_tailoring_run_revision_requires_success"), "tailoring_run", type_="check"
    )
    op.drop_constraint(op.f("ck_tailoring_run_cv_revision_pairs"), "tailoring_run", type_="check")
    op.drop_constraint(
        op.f("ck_tailoring_run_cover_letter_revision_pairs"), "tailoring_run", type_="check"
    )
    op.drop_column("tailoring_run", "cover_letter_edited_at")
    op.drop_column("tailoring_run", "cv_edited_at")
    op.drop_column("tailoring_run", "edited_cover_letter")
    op.drop_column("tailoring_run", "edited_cv")
    op.drop_column("tailoring_run", "version")
