"""add tracking application

Revision ID: 7e43a47327ec
Revises: b1b518fe84b1
Create Date: 2026-10-05 19:27:37.586522

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 3.1 (ADR-0029, technical plan §5): one new table, `tracking_application` — a signed-in user's
card for one succeeded tailoring run. The reasons for every column and constraint are on the `Table`
in `infrastructure/persistence/mapping/tracking/tracked_application.py`, which is what ships; take the
authoritative text from there.

**Expand-only.** One table nothing has ever written, and its one index. No existing column,
constraint or index is created, altered or dropped, so the running 2.5 code — which does not know the
table exists — is unaffected through the two-version deploy window by construction.

**One `NOT NULL` owner column and no `guest_session_id`** (plan §0.5): the deliberate contrast with
the two-nullable-FKs-plus-`exactly_one_owner` shape of 2.2/2.3 (ADR-0022). The FK to `identity_user`
is `ON DELETE CASCADE`, so account erasure takes the cards; nothing references a guest table, so the
purge and the claim cannot reach this one.

**No foreign key on `tailoring_run_id`** (ADR-0014/0016/0023: contexts' tables are not fused). The
repository's two-lock pattern closes the race an FK would (plan §0.7).

**Plain `CREATE INDEX`, not `CONCURRENTLY`.** The index is on the table created a statement earlier in
the same transaction; CLAUDE.md's one-transaction-per-revision note applies only to populated tables.

**Downgrade refuses while any row exists** — 2.2's and 2.3's precedent for *kept* user data
(`1a2676aa3759`, `03494836ce30`), and the contrast with `b1b518fe84b1`, whose one-time tokens may be
dropped. A card is something a user chose to keep; a rollback must never delete it to make a schema
fit. On an empty table it drops the index and the table. A table is dropped, never a column, so it
consumes no dropped-column slots (PR #12).

**Reviewed line by line.** The draft's content was right: `render_item` rendered the four
`TypeDecorator` columns as their `impl`s (`postgresql.UUID(as_uuid=True)` for both ids and
`user_id`, `sa.String(16)` for the stage, `sa.Text()` for the title), both instants as
`postgresql.TIMESTAMP(timezone=True, precision=0)`, every name the one plan §5 lists, wrapped in
`op.f()` so no naming convention is applied on top. Nothing invented: no drop, no alteration of an
existing object. Changed from the draft: the index name wrapped in `op.f()` like every other name; the
downgrade's refusal added; rewrapped for `ruff format`, the autogenerate markers removed, comments
added.

Verified against the dev database (at `b1b518fe84b1`): `alembic upgrade head`, `alembic downgrade -1`
on an empty table, `alembic upgrade head`; the downgrade refused with one row present; `alembic check`
reports no difference against the mapping. From empty, the test suite's `_migrated` fixture runs the
whole chain on every session.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

revision: str = "7e43a47327ec"
down_revision: str | None = "b1b518fe84b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_REFUSAL = (
    "refusing to downgrade 7e43a47327ec: tracking_application holds tracked applications, which "
    "users keep until they delete them, and the previous schema has nowhere to put them. Erase "
    "those accounts first (python -m tailorcraft.cli erase-account), or do not downgrade — this "
    "migration never deletes data to make a downgrade fit."
)


def upgrade() -> None:
    op.create_table(
        "tracking_application",
        # `TrackedApplicationIdType.impl`. Application-assigned UUIDv7 (ADR-0007): no default.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `UserIdType.impl`. NOT NULL, and there is no guest column (plan §0.5).
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `TrackedRunRefType.impl`. No FK (plan §0.7); unique below — one card per run.
        sa.Column("tailoring_run_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `ApplicationStageType.impl` — `VARCHAR(16)` + a CHECK, not a native enum.
        sa.Column("stage", sa.String(length=16), nullable=False),
        # `ApplicationTitleType.impl`; the bound is the CHECK below.
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("tracked_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column(
            "stage_changed_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False
        ),
        # The mapper's `version_id_col`; the default serves hand-written inserts only.
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "stage IN ('to_apply','applied','interviewing','offer','rejected','withdrawn')",
            name=op.f("ck_tracking_application_stage_known"),
        ),
        sa.CheckConstraint(
            "stage_changed_at >= tracked_at",
            name=op.f("ck_tracking_application_stage_changed_after_tracked"),
        ),
        sa.CheckConstraint(
            "title IS NULL OR char_length(title) BETWEEN 1 AND 120",
            name=op.f("ck_tracking_application_title_length"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_user.id"],
            name=op.f("fk_tracking_application_user_id_identity_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_application")),
        sa.UniqueConstraint(
            "tailoring_run_id", name=op.f("uq_tracking_application_tailoring_run_id")
        ),
    )
    # The board query's `WHERE` + `ORDER BY`; its leading column serves `count_for_user` and the
    # FK cascade too.
    op.create_index(
        op.f("ix_tracking_application_user_id_stage_changed_at"),
        "tracking_application",
        ["user_id", sa.literal_column("stage_changed_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )


def downgrade() -> None:
    # Taken before the look, so no card can be inserted between the check and the `DROP TABLE`
    # (which needs `ACCESS EXCLUSIVE` anyway).
    op.execute("LOCK TABLE tracking_application IN ACCESS EXCLUSIVE MODE")
    condition_sql = "SELECT 1 FROM tracking_application"
    if context.is_offline_mode():
        # A generated script has no connection to ask, so the refusal travels in the SQL itself.
        # Interpolates only this module's constants, none of which holds a quote.
        op.execute(
            f"DO $$ BEGIN IF EXISTS ({condition_sql}) "
            f"THEN RAISE EXCEPTION '{_REFUSAL}'; END IF; END $$"
        )
    elif op.get_bind().execute(sa.text(f"SELECT EXISTS ({condition_sql})")).scalar_one():
        raise RuntimeError(_REFUSAL)

    op.drop_index(
        op.f("ix_tracking_application_user_id_stage_changed_at"),
        table_name="tracking_application",
    )
    op.drop_table("tracking_application")
