"""add export job

Revision ID: fa1bef4468bf
Revises: 274e4abc5d73
Create Date: 2026-09-17 14:05:28.680093

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 1.5 (ADR-0016): one new table, `export_job`, and nothing else. Fifteen columns, seven CHECKs,
one UNIQUE, one cascading foreign key and three indexes — one of them partial. The reasons for every
one of them are on the `Table` in `infrastructure/persistence/mapping/export/export_job.py`, which is
what ships; take the authoritative text from there. What follows is only what a reader of *this* file
needs.

**A job row is a record of one request to render one document of one run into one file.** It holds
ids, enums, integers, instants and a storage key, and **no PII** (ADR-0016 §4) — no name, no
document text, no path, no client IP. That is a property to defend the next time a column is
proposed here, not a coincidence: §3 refused twice to snapshot the document onto the job.

**Two columns carry the retention contract 1.6 consumes** (AC-22, AC-23): `guest_session_id` is
`NOT NULL` with `ON DELETE CASCADE` and indexed, so purging an expired session deletes its export
jobs in the same statement; and `file_key` is `FileRef.for_export(id, format).key` for every `ready`
row, so 1.6 can read the keys of an expiring session's jobs before the cascade or reconstruct them
from the ids afterwards, and unlink **after** the rows are gone (ADR-0006 §2's order).

**Seven CHECKs, one per column, and the "one per column" is the point** (1.3's AC-4 amendment). The
tempting form compares a status against a *conjunction* — `(status = 'ready') = (file_key IS NOT
NULL AND byte_size IS NOT NULL AND render_duration_ms IS NOT NULL)` — and a non-`ready` row holding
exactly one of the three satisfies it (`false = false`), so Postgres would accept
`UPDATE export_job SET byte_size = 1` on a failed job. XJ-3 is "a ready job has all three; half a
row is not a state", and half a row is exactly what the conjunction admits.

**Purely additive and expand-only.** A new table nothing has ever written; no existing column,
constraint or index is altered or dropped. The previous application version does not know this table
exists and never touches it, so the two-version deploy window is safe by construction — this is the
easiest migration in the project so far, and the first since `33d8cf628221` to create a table.

**Plain `CREATE INDEX`, not `CREATE INDEX CONCURRENTLY`, and here that needs no expiry date.**
`3d0b70b7837f` left a standing note that *the next index on `tailoring_run`* should be built
concurrently, because a plain build holds a `SHARE` lock while scanning the whole heap and that wait
grows with a live table. These three indexes are on a table created three statements earlier in the
same transaction: there is no heap, no concurrent writer and nothing to lock out. The note still
stands for `tailoring_run`; it does not reach here.

**Reviewed line by line. The draft was the best one yet — `render_item` (1.4's P1) did its job for
the first time on a whole table** — and two things still needed a hand.

  1. **`postgresql_where` on `drop_index`**, the identical fault `3d0b70b7837f`'s draft had.
     `DROP INDEX` takes no predicate, so the argument is inert; it is removed rather than left,
     because leaving it suggests a predicate matters on the way down and the next person copies it.
  2. **The seven CHECKs came out sorted by their expression text**, not in the order the `Table`
     declares them, so `format_is_queued` and `run_version_positive` — the two structural rules,
     first in the mapping — landed sixth and seventh, under the five status pairings. Restored to
     the declared order so this file and the mapping read the same way. Cosmetic, and worth the
     minute: the next reader diffs these two files against each other.

Everything else came out correct and was checked rather than assumed:

  - every `TypeDecorator` column rendered as its **`impl`** — `postgresql.UUID(as_uuid=True)`,
    `sa.String(16/8/32/512)`, `postgresql.TIMESTAMP(timezone=True, precision=0)` — not as an
    unimportable class reference. That is `render_item`; the first three revisions were hand-fixed
    for exactly this;
  - the partial index's **`postgresql_where=sa.text("status = 'rendering'")`** is present on
    `create_index`. It survives because the `Index` declares its predicate as a `text()` literal,
    which autogenerate copies verbatim, rather than as an expression over the decorated `status`
    column;
  - the **`UNIQUE` on `file_key`** is present, as `sa.UniqueConstraint` inside `create_table`;
  - the FK's **`ondelete='CASCADE'`** is present, spelled on the `ForeignKeyConstraint`;
  - `server_default=sa.text('1')` on `version`, and `TIMESTAMP(0) WITH TIME ZONE` on all three
    instants — whole-second per the `Clock` contract, so a round trip can never change a value;
  - no drop of anything that already exists, and no change to `tailoring_run`.

Changed from the draft beyond those two fixes: `op.f()` around the partial index's name (it marks
the name as final, so no naming convention is ever applied on top of it — the same call the earlier
revisions make), rewrapped for `ruff format`, the autogenerate marker comments removed, and comments
added.

Verified against the dev database, which started at `274e4abc5d73`: `alembic upgrade head` (table,
15 columns, 7 CHECKs, the UNIQUE, the FK with `ON DELETE CASCADE`, 3 indexes with the partial one's
`WHERE ((status)::text = 'rendering'::text)` present in `pg_indexes`), then `alembic downgrade 274e4abc5d73`
(table and all three indexes gone, `alembic_version` back at `274e4abc5d73`, `tailoring_run`
untouched), then `alembic upgrade head` again (everything back, byte-identical `pg_indexes` and
`pg_constraint` rows). `alembic check` then reported no new upgrade operations, so the mapping and
the migrated schema agree.

**Also verified against a genuinely empty database** (a throwaway created for it and dropped
afterwards), because "applies on top of `274e4abc5d73`" and "applies from `base`" are two different
claims and only the second is what a fresh environment does: the whole chain ran
`base -> fa1bef4468bf`, and the resulting `pg_indexes` and `pg_constraint` rows were byte-identical
to the dev database's.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fa1bef4468bf"
down_revision: str | None = "274e4abc5d73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "export_job",
        # `ExportJobIdType.impl` — a native Postgres UUID. Application-assigned UUIDv7 from
        # `ExportJobRepository.next_identity()` (ADR-0007): no server default, no sequence. Here the
        # id does a second job — it is the sole input to the file's storage key
        # (`FileRef.for_export`, XJ-7), so `id` and `file_key` are two spellings of one fact.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `GuestSessionIdType.impl` — likewise. Half of the retention contract (module docstring).
        sa.Column("guest_session_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `TailoringRunIdType.impl`, deliberately **without** a foreign key to `tailoring_run`: an
        # aggregate references another aggregate by identity, and both tables already cascade from
        # `identity_guest_session`, so an FK here would add a write-time check and a second cascade
        # path for a guarantee the session FK already gives. `tailoring_run` made the same call for
        # `base_cv_id` / `job_posting_id`; the mapping module records the reasoning in full.
        sa.Column("tailoring_run_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `TailoredDocumentKindType.impl` — VARCHAR(16). The decorator lives in `types/tailoring.py`
        # rather than `types/export.py`, because the enum is `tailoring`'s; this is its first column
        # in any table.
        sa.Column("document", sa.String(length=16), nullable=False),
        # `ExportFormatType.impl` — VARCHAR(8), deliberately not a native Postgres ENUM (adding a
        # member to one takes a lock), and constrained below to the two *queued* formats.
        sa.Column("format", sa.String(length=8), nullable=False),
        # The run's `version` at request time — the number `was_requested_for` compares against to
        # decide `source_changed` (ADR-0016 (b)). Unrelated to `version` at the bottom of this list.
        sa.Column("run_version", sa.Integer(), nullable=False),
        # `ExportJobStatusType.impl` and `ExportFailureReasonType.impl`. The aggregate's twelve-cell
        # transition table is the first enforcement; the CHECKs below are what bind a hand-written
        # UPDATE.
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_reason", sa.String(length=32), nullable=True),
        # `FileRefType.impl` — VARCHAR(512), **reused** from `types/shared.py` where 1.1 put it for
        # exactly this moment. One value object, one decorator, so the storage grammar cannot be
        # re-validated by two different rules on the way out of two tables. (The technical plan's
        # column table says VARCHAR(64); the reuse won on purpose, and the 512 was chosen *for* it.)
        sa.Column("file_key", sa.String(length=512), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        # Milliseconds, on purpose, and meant to look inconsistent with the three whole-second
        # timestamps below — the same deliberate inconsistency `tailoring_run.llm_duration_ms`
        # carries. This is not a clock reading; it is a duration measured with `time.perf_counter()`,
        # and a render budgeted in single-digit seconds has no signal left at whole-second
        # resolution. Do not "make it consistent".
        sa.Column("render_duration_ms", sa.Integer(), nullable=True),
        # Whole-second by contract (ADR-0007): the `Clock` truncates at the source, so a database
        # round trip can never change a value and an equality assertion on a reloaded job cannot
        # fail by microseconds. It is also why both ordered reads in the repository break ties on
        # `id` — two jobs requested in the same second are ordinary here, not exotic.
        sa.Column("requested_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        # The optimistic-concurrency counter the mapping declares as `version_id_col` with
        # `version_id_generator=False` (ADR-0015 §3, XJ-6): the aggregate owns the number, the
        # mapper only checks it. `DEFAULT 1` is for hand-written INSERTs — unlike
        # `tailoring_run.version` it has no deploy window to serve, since the table and the column
        # ship together — and is kept so the two `version` columns behave identically under `psql`.
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        # **The third lock on XJ-2** ("a job may not exist for an inline format"), after
        # `ExportJob.request` and `FileRef.for_export`, and the only one that binds a hand-written
        # INSERT. A membership test over the two queued formats rather than a negation of the two
        # inline ones: `format NOT IN ('md','txt')` would silently admit a fifth format.
        sa.CheckConstraint(
            "format IN ('pdf','docx')",
            name=op.f("ck_export_job_format_is_queued"),
        ),
        # XJ-8: a run version counts from 1, so 0 or a negative is a number no run ever had.
        # `ExportJob.request` raises `InvalidRunVersion` below 1; this is the same rule where Python
        # cannot reach. No upper bound — no number of edits makes a job invalid.
        sa.CheckConstraint(
            "run_version >= 1",
            name=op.f("ck_export_job_run_version_positive"),
        ),
        # XJ-3, three times, one column each (module docstring). Each is an equality between two
        # predicates rather than an implication, so one expression rejects **both** bad pairings: a
        # ready job missing its size, and a queued job that somehow has one.
        sa.CheckConstraint(
            "(status = 'ready') = (file_key IS NOT NULL)",
            name=op.f("ck_export_job_file_key_matches_status"),
        ),
        sa.CheckConstraint(
            "(status = 'ready') = (byte_size IS NOT NULL)",
            name=op.f("ck_export_job_byte_size_matches_status"),
        ),
        sa.CheckConstraint(
            "(status = 'ready') = (render_duration_ms IS NOT NULL)",
            name=op.f("ck_export_job_render_duration_matches_status"),
        ),
        sa.CheckConstraint(
            "(status = 'failed') = (failure_reason IS NOT NULL)",
            name=op.f("ck_export_job_failure_reason_matches_status"),
        ),
        # The two terminal statuses are exactly the two that carry a `completed_at`. **`started_at`
        # gets no such constraint, deliberately**: `mark_failed` is legal from `queued`, and two
        # failures are recorded from there — a refused enqueue (`not_queued`) and a run whose
        # documents changed under a job that never started (`source_changed`). A constraint tying
        # the two would forbid both.
        sa.CheckConstraint(
            "(status IN ('ready','failed')) = (completed_at IS NOT NULL)",
            name=op.f("ck_export_job_completed_at_matches_terminal_status"),
        ),
        # ON DELETE CASCADE is how this table joins ADR-0006's retention story without any retention
        # code in this slice: purging an expired session row deletes its export jobs in the same
        # statement, so 1.6 needs no new predicate.
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["identity_guest_session.id"],
            name=op.f("fk_export_job_guest_session_id_identity_guest_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_job")),
        # **A corruption detector rather than a business rule.** `file_key` is a pure function of
        # `id`, which is the primary key, so two rows can only share a key if something wrote a key
        # it did not derive — and this turns that into a failed write instead of two jobs whose
        # downloads silently serve one file. Free on the mostly-NULL column: PostgreSQL's btree
        # skips NULLs for uniqueness, so every queued, rendering and failed row is out of it.
        sa.UniqueConstraint("file_key", name=op.f("uq_export_job_file_key")),
    )
    # Two readers: `count_for_session` (the `TooManyExportJobs` cap) and the cascade above.
    op.create_index(
        op.f("ix_export_job_guest_session_id"), "export_job", ["guest_session_id"], unique=False
    )
    # Two readers: `list_for_run` (the reattach-after-refresh endpoint) and `find_latest_for_key`
    # (the idempotency lookup, which filters `document` and `format` on top). The composite index
    # that would serve the second exactly is named in the mapping module as the change to make if a
    # run ever holds more than a few dozen jobs.
    op.create_index(
        op.f("ix_export_job_tailoring_run_id"), "export_job", ["tailoring_run_id"], unique=False
    )
    # The partial index for the stale-render sweep, the twin of `3d0b70b7837f`'s. Partial because
    # the `rendering` set is tiny whatever the table's size — a row is in it only while a worker
    # holds the render — so the terminal rows that are nearly the whole table never enter it.
    # `list_stale_rendering` must state `'rendering'` as a **literal** for the planner to use this,
    # and it does (`literal_execute=True`); a generic plan holding `status = $1` cannot prove the
    # query's WHERE implies the index's.
    op.create_index(
        op.f("ix_export_job_rendering_started_at"),
        "export_job",
        ["started_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'rendering'"),
    )


def downgrade() -> None:
    # Indexes first, then the table — `DROP TABLE` would take them anyway, but dropping them
    # explicitly keeps the down path a mirror of the up one and readable as such.
    #
    # **No `postgresql_where` on any of these**, and its absence is a correction rather than an
    # omission: the draft carried the predicate onto `drop_index`, exactly as `3d0b70b7837f`'s did.
    # `DROP INDEX` takes no predicate, so the argument is inert and only suggests one matters here.
    op.drop_index(op.f("ix_export_job_rendering_started_at"), table_name="export_job")
    op.drop_index(op.f("ix_export_job_tailoring_run_id"), table_name="export_job")
    op.drop_index(op.f("ix_export_job_guest_session_id"), table_name="export_job")
    # The seven CHECKs, the UNIQUE and the FK go with the table; none of them is named on a table
    # that outlives this migration, so there is nothing to drop first.
    op.drop_table("export_job")
