"""add owner and label to base cv

Revision ID: 1a2676aa3759
Revises: 66c9e18acc5c
Create Date: 2026-09-25 12:20:43.867110

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 2.2 (ADR-0022, technical plan §5, AC-13): a base CV's owner is a guest session **or** a user.
The domain models that as a sum type; a foreign key has one target table, so the table stores a
product of two nullable owner columns and a CHECK restores "exactly one". The reasons for every
column and constraint are on the `Table` in `infrastructure/persistence/mapping/intake/base_cv.py`,
which is what ships; this docstring is what a reader of *this* file needs.

**Expand-only, and backward-compatible with the running 2.1 code (AC-14).** 2.1 inserts only guest
rows — no `user_id`, a non-null `guest_session_id` — which every new constraint accepts; it reads
only by `guest_session_id` or by id; and its purge and orphan sweep are owner-blind in exactly the
safe directions (the cascade cannot reach a row with `guest_session_id IS NULL`, and the cross-check
reads `file_key` for every row). Nothing is renamed, retyped or dropped.

**The order is the point** (technical plan §5):

  1. Add the three columns, all nullable and without a default — a catalog-only change, no rewrite.
  2. The index and the foreign key on `user_id`. Every existing row has `user_id IS NULL`, so the
     FK's validation scan has nothing to check.
  3. Both CHECKs `NOT VALID`, then `VALIDATE CONSTRAINT` each. `NOT VALID` enforces the constraint
     on new writes at once while skipping the scan, and `VALIDATE` scans under
     `SHARE UPDATE EXCLUSIVE`, which does not block reads or writes. Every existing row has exactly
     one owner (its guest session) and no label, so validation passes. Immaterial at today's row
     counts; the habit costs nothing, and the day it matters nobody remembers to start it.
  4. `DROP NOT NULL` on `guest_session_id` **last**. Until this line runs the old `NOT NULL` still
     refuses an ownerless row; from this line on `ck_intake_base_cv_exactly_one_owner` does. There
     is no instant at which a row with no owner is permitted.

**Plain `CREATE INDEX`, not `CONCURRENTLY`**: Alembic runs a revision in one transaction, which
`CONCURRENTLY` refuses, and `intake_base_cv` holds at most five rows per live guest session (the
purge deletes the rest), so the write lock lasts milliseconds. The release script stops worker and
beat across the migration window as always.

**`copied_from_base_cv_id` carries no foreign key, on purpose** — the one edge that would cross
owners (a guest working copy → a user's saved CV). Provenance, not a link (ADR-0022).

**The downgrade refuses** when any user-owned row exists, raising a sentence instead of deleting
data. Restoring `NOT NULL` on `guest_session_id` would otherwise fail half-way on the first saved
CV, and the "fix" someone would reach for at that moment is a `DELETE` of registered users' CVs.
With no user-owned row, every row is a guest row with no label, so dropping `user_id` and `label`
loses nothing; `copied_from_base_cv_id` goes with its provenance, which only ever named a source
that — by the same check — no longer exists as a saved CV.

**Reviewed line by line against the autogenerate draft.** `render_item` rendered every
`TypeDecorator` as its `impl` — `postgresql.UUID(as_uuid=True)` for `user_id` and
`copied_from_base_cv_id`, `sa.String(length=80)` for `label` — so there was no decorator reference
to replace. Every constraint name matches plan §5 and the naming convention, wrapped in `op.f()` so
no convention is applied on top. Changed from the draft:

  1. **The draft ran `alter_column(nullable=True)` first**, before either CHECK existed — for the
     length of the revision nothing refused an ownerless row. Moved to the end (step 4).
  2. **The draft created both CHECKs validated inline.** Now `postgresql_not_valid=True` plus an
     explicit `VALIDATE CONSTRAINT` each (step 3).
  3. **The draft's downgrade restored `NOT NULL` unconditionally.** It now locks the table and
     refuses on a user-owned row first; then drops the CHECKs, the FK and the index before the
     columns they name (a multi-column CHECK blocks a plain `DROP COLUMN`).
  4. Rewrapped for `ruff format`, the autogenerate marker comments removed, comments added.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

revision: str = "1a2676aa3759"
down_revision: str | None = "66c9e18acc5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_REFUSAL = (
    "refusing to downgrade 1a2676aa3759: intake_base_cv holds saved CVs owned by registered users, "
    "and the previous schema cannot represent them (guest_session_id NOT NULL). Erase those "
    "accounts first (python -m tailorcraft.cli erase-account), or do not downgrade — this "
    "migration never deletes data to make a downgrade fit."
)


def upgrade() -> None:
    # 1. Columns. Nullable, no default: no table rewrite.
    # `UserIdType.impl`.
    op.add_column(
        "intake_base_cv", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    # `BaseCvLabelType.impl` — `BaseCvLabel`'s own 80-character bound.
    op.add_column("intake_base_cv", sa.Column("label", sa.String(length=80), nullable=True))
    # `BaseCvIdType.impl`. No FK (module docstring).
    op.add_column(
        "intake_base_cv",
        sa.Column("copied_from_base_cv_id", postgresql.UUID(as_uuid=True), nullable=True),
    )

    # 2. The user half's index and foreign key.
    op.create_index(op.f("ix_intake_base_cv_user_id"), "intake_base_cv", ["user_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_intake_base_cv_user_id_identity_user"),
        "intake_base_cv",
        "identity_user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # 3. The CHECKs: enforced on new writes at once, existing rows validated separately.
    op.create_check_constraint(
        op.f("ck_intake_base_cv_exactly_one_owner"),
        "intake_base_cv",
        "num_nonnulls(guest_session_id, user_id) = 1",
        postgresql_not_valid=True,
    )
    op.create_check_constraint(
        op.f("ck_intake_base_cv_label_only_when_user_owned"),
        "intake_base_cv",
        "label IS NULL OR user_id IS NOT NULL",
        postgresql_not_valid=True,
    )
    op.execute("ALTER TABLE intake_base_cv VALIDATE CONSTRAINT ck_intake_base_cv_exactly_one_owner")
    op.execute(
        "ALTER TABLE intake_base_cv VALIDATE CONSTRAINT ck_intake_base_cv_label_only_when_user_owned"
    )

    # 4. Last: from here on the CHECK, not `NOT NULL`, refuses an ownerless row.
    op.alter_column("intake_base_cv", "guest_session_id", existing_type=sa.UUID(), nullable=True)


def downgrade() -> None:
    # Taken before the look, so no saved CV can be inserted between the check and the `SET NOT
    # NULL` below. Every `ALTER TABLE` that follows needs `ACCESS EXCLUSIVE` anyway.
    op.execute("LOCK TABLE intake_base_cv IN ACCESS EXCLUSIVE MODE")
    if context.is_offline_mode():
        # A generated script has no connection to ask, so the refusal travels in the SQL itself.
        op.execute(
            "DO $$ BEGIN IF EXISTS (SELECT 1 FROM intake_base_cv WHERE user_id IS NOT NULL) "  # noqa: S608 -- interpolates only the module constant `_REFUSAL`, which holds no quote; no input reaches this string
            f"THEN RAISE EXCEPTION '{_REFUSAL}'; END IF; END $$"
        )
    else:
        user_owned = op.get_bind().execute(
            sa.text("SELECT count(*) FROM intake_base_cv WHERE user_id IS NOT NULL")
        )
        if user_owned.scalar_one() > 0:
            raise RuntimeError(_REFUSAL)

    # Constraints before the columns they name.
    op.drop_constraint(
        op.f("ck_intake_base_cv_label_only_when_user_owned"), "intake_base_cv", type_="check"
    )
    op.drop_constraint(op.f("ck_intake_base_cv_exactly_one_owner"), "intake_base_cv", type_="check")
    op.drop_constraint(
        op.f("fk_intake_base_cv_user_id_identity_user"), "intake_base_cv", type_="foreignkey"
    )
    op.drop_index(op.f("ix_intake_base_cv_user_id"), table_name="intake_base_cv")
    # Safe now: no user-owned row, and the CHECK guaranteed every other row a guest owner.
    op.alter_column("intake_base_cv", "guest_session_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("intake_base_cv", "copied_from_base_cv_id")
    op.drop_column("intake_base_cv", "label")
    op.drop_column("intake_base_cv", "user_id")
