"""add identity user and login

Revision ID: 66c9e18acc5c
Revises: fa1bef4468bf
Create Date: 2026-09-23 21:34:36.671746

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 2.1 (ADR-0020, technical plan §5): three new tables for registered users and their sign-ins,
and nothing else. The reasons for every column and constraint are on the `Table`s in
`infrastructure/persistence/mapping/identity/user.py` and `login.py`, which is what ships; take the
authoritative text from there. What follows is what a reader of *this* file needs.

**Purely additive and expand-only (AC-14).** Three tables nothing has ever written; no existing
column, constraint or index is created, altered or dropped. The previous application version does
not know these tables exist, so the two-version deploy window is safe by construction.

**No foreign key references `identity_guest_session` (AC-15).** The only foreign keys point up the
identity chain — `identity_retired_refresh_token.login_id` → `identity_login.id`, and
`identity_login.user_id` → `identity_user.id` — each `ON DELETE CASCADE`, so the 24-hour guest purge
has no path into a registered user's rows, and revoking a login is one `DELETE` (ADR-0020).

**Three columns carry a credential-shaped value**: `identity_user.password_hash` (a PHC string) and
the two `CHAR(64)` token-hash columns. No plaintext password or refresh token has a column anywhere,
and that is a property to defend the next time a column is proposed here.

**No `ix_identity_login_expires_at`**, deliberately (technical plan §5): the expired-login sweep has
no slice yet (R-8), and an index nobody queries is write cost on a row updated every fifteen minutes
per open tab. Build it with the sweep.

**Plain `CREATE INDEX`, not `CONCURRENTLY`**: both indexes are on tables created earlier in the same
transaction — no heap, no concurrent writer, nothing to lock out.

**Downgrade drops tables, never columns**, in reverse foreign-key order, so it does not consume
dropped-column slots and cannot feed the local `TooManyColumnsError` problem (PR #12).

**Reviewed line by line.** `render_item` did its job again: every `TypeDecorator` column came out as
its `impl` — `postgresql.UUID(as_uuid=True)` for the three ids, `sa.String(254)` for the email,
`sa.String(512)` for the password hash, `sa.CHAR(64)` for both token hashes — and every instant as
`postgresql.TIMESTAMP(timezone=True, precision=0)`. Every name is the one plan §5 lists, wrapped in
`op.f()` so no naming convention is applied on top of it. Changed from the draft:

  1. **`identity_login`'s three CHECKs came out sorted by expression text**, putting
     `rotated_iff_rotated` first. Restored to the order the `Table` declares them, so this file and
     the mapping diff cleanly against each other (the same fix `fa1bef4468bf` needed).
  2. Rewrapped for `ruff format`, the autogenerate marker comments removed, comments added.

Verified against the dev database, which started at `fa1bef4468bf`: `alembic upgrade head`, then
`alembic downgrade -1` (all three tables gone, `alembic_version` back at `fa1bef4468bf`), then
`alembic upgrade head` again, with the `pg_constraint`, `pg_indexes` and `information_schema.columns`
rows for the three tables byte-identical before and after the round trip. Read from
`pg_constraint`, not from this docstring: both foreign keys have `confdeltype = 'c'`, and **zero**
constraints on the three tables reference `identity_guest_session` (AC-15). `alembic check` then
reported no new upgrade operations, so the mapping and the migrated schema agree. **From empty**:
the test suite's `_migrated` fixture drops `public` and runs the whole chain `base -> 66c9e18acc5c`
on every session, and did so green.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "66c9e18acc5c"
down_revision: str | None = "fa1bef4468bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "identity_user",
        # `UserIdType.impl`. Application-assigned UUIDv7 (ADR-0007): no server default.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `EmailAddressType.impl` — always the normalized form; the UNIQUE below is the registration
        # race's referee (AC-16), recognised by name in `SqlAlchemyUserRepository.add`.
        sa.Column("email", sa.String(length=254), nullable=False),
        # `PasswordHashType.impl` — a PHC string, never a plaintext.
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column(
            "password_updated_at",
            postgresql.TIMESTAMP(timezone=True, precision=0),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(btrim(email))", name=op.f("ck_identity_user_email_normalized")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_user")),
        sa.UniqueConstraint("email", name=op.f("uq_identity_user_email")),
    )
    op.create_table(
        "identity_login",
        # `LoginIdType.impl` / `UserIdType.impl`.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        # Absolute: rotation never moves it (OQ-9).
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        # `TokenHashType.impl` — the SHA-256 hex of the current refresh token.
        sa.Column("current_token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("rotated_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        # Optimistic concurrency, checked by the repository's own `WHERE version = :v`. No
        # `server_default`: the column is born with its table, so no older writer exists.
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_identity_login_expires_after_created")
        ),
        sa.CheckConstraint("generation >= 1", name=op.f("ck_identity_login_generation_positive")),
        sa.CheckConstraint(
            "(generation = 1) = (rotated_at IS NULL)",
            name=op.f("ck_identity_login_rotated_iff_rotated"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_user.id"],
            name=op.f("fk_identity_login_user_id_identity_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_login")),
        sa.UniqueConstraint(
            "current_token_hash", name=op.f("uq_identity_login_current_token_hash")
        ),
    )
    op.create_index(op.f("ix_identity_login_user_id"), "identity_login", ["user_id"], unique=False)
    op.create_table(
        "identity_retired_refresh_token",
        # `TokenHashType.impl`, and the primary key: the lookup column is the identity. Its refusal
        # is the second half of I-25, recognised by name in `save_rotation`.
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("login_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("retired_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.ForeignKeyConstraint(
            ["login_id"],
            ["identity_login.id"],
            name=op.f("fk_identity_retired_refresh_token_login_id_identity_login"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_identity_retired_refresh_token")),
    )
    op.create_index(
        op.f("ix_identity_retired_refresh_token_login_id"),
        "identity_retired_refresh_token",
        ["login_id"],
        unique=False,
    )


def downgrade() -> None:
    # Reverse foreign-key order. Dropping a table drops its indexes; they are named explicitly
    # anyway so this reads as the exact inverse of `upgrade`.
    op.drop_index(
        op.f("ix_identity_retired_refresh_token_login_id"),
        table_name="identity_retired_refresh_token",
    )
    op.drop_table("identity_retired_refresh_token")
    op.drop_index(op.f("ix_identity_login_user_id"), table_name="identity_login")
    op.drop_table("identity_login")
    op.drop_table("identity_user")
