"""add tailoring run

Revision ID: 33d8cf628221
Revises: 088f1ff1f00f
Create Date: 2026-09-11 09:33:47.322021

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

This revision is purely additive: one new table, one FK, one index, three check constraints, and
nothing existing is altered or dropped. Expand -> migrate -> contract is therefore trivially
satisfied — the previous application version simply never reads `tailoring_run`, which is what makes
the brief two-version deploy window safe.

Hand-fixed after autogenerate, and **the same failure as the first two revisions, for the third
time, because nothing about it was fixed at the source**: ten of the sixteen columns — every column
backed by a `TypeDecorator` (`TailoringRunIdType`, `GuestSessionIdType`, `BaseCvIdType`,
`JobPostingIdType`, `TailoringRunStatusType`, `TailoringFailureReasonType`, `TailoredCvType`,
`CoverLetterType`, `ModelNameType`, `PromptVersionType`) — came out as a bare reference to the Python
class, e.g.
`tailorcraft.infrastructure.persistence.types.tailoring.TailoringRunIdType()`, with no
`import tailorcraft` anywhere in the file. That is not a rendering nicety to tidy up; the generated
module raises `NameError: name 'tailorcraft' is not defined` the moment Alembic `exec`s it.

Every such column below is rewritten to the `TypeDecorator`'s own `impl` — the column's actual wire
type in PostgreSQL — which is also the structurally right thing: a migration describes the *schema*,
not the ORM layer that happens to produce it today. If `TailoredCvType` were replaced tomorrow with a
different decorator over the same `TEXT`, this file should not change, and now it would not have to.

The three `Integer` columns, `TIMESTAMP(timezone=True, precision=0)`, the three CHECKs, the FK and
the index all came out of autogenerate correct, because `tailoring_run_table` declares those
directly rather than through a `TypeDecorator`. The only other change is formatting: the draft's
one-line-per-call style is rewrapped to satisfy `ruff format`, and comments are added.

Verified by hand against a throwaway database at 088f1ff1f00f: `alembic upgrade head`, then
`alembic downgrade -1`, then `alembic upgrade head` again.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "33d8cf628221"
down_revision: str | None = "088f1ff1f00f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tailoring_run",
        # `TailoringRunIdType.impl` — a native Postgres UUID. Application-assigned UUIDv7 from
        # `TailoringRunRepository.next_identity()` (ADR-0007): no server default, no sequence. The
        # database is told the id; it never invents one.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `GuestSessionIdType.impl` — likewise.
        sa.Column("guest_session_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `BaseCvIdType.impl` and `JobPostingIdType.impl` — likewise, and deliberately **without a
        # foreign key** to `intake_base_cv` / `posting_job_posting`. An aggregate references another
        # aggregate by identity, not by a database relationship; and all three tables already cascade
        # from `identity_guest_session`, so an FK here would add a write-time check and a second
        # cascade path for a guarantee the session FK already gives. The mapping module records both
        # reasons at length, plus the trigger to revisit them.
        sa.Column("base_cv_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_posting_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `TailoringRunStatusType.impl` — VARCHAR(16), deliberately not a native Postgres ENUM: the
        # same call `intake_base_cv.status` and `posting_job_posting.source` make, because adding a
        # member to a native enum takes a lock. The aggregate's transition table and the CHECKs below
        # are the enforcement.
        sa.Column("status", sa.String(length=16), nullable=False),
        # `TailoringFailureReasonType.impl`. Non-null iff the run failed (see the CHECK).
        sa.Column("failure_reason", sa.String(length=32), nullable=True),
        # `TailoredCvType.impl` and `CoverLetterType.impl` — TEXT, not a bounded VARCHAR: on
        # PostgreSQL they are the same storage and the same speed, and a length here would be a
        # second home for the domain's floors and ceilings. **Both columns are PII** (Constitution
        # §8) — a tailored CV is a person's employment history rewritten and a cover letter names
        # where they want to work. Two named columns rather than one JSONB blob because they are two
        # named things with two different rules, not a schemaless bag.
        sa.Column("tailored_cv", sa.Text(), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        # `ModelNameType.impl` and `PromptVersionType.impl`, then three plain integers: the five
        # columns behind `TailoringRun.metrics`. All five are NULL together on every path but a
        # succeeded run — a partially filled metrics row would show up in a token-spend total as a
        # real number nothing was paid for.
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        # Milliseconds, on purpose, and it is meant to look inconsistent with the three whole-second
        # timestamps below: this is not a clock reading, it is a duration the adapter measures with
        # `time.perf_counter()`, and Constitution §7's 15-second budget cannot be defended at
        # whole-second resolution. Do not "make it consistent".
        sa.Column("llm_duration_ms", sa.Integer(), nullable=True),
        # Whole-second by contract (ADR-0007): the `Clock` port truncates at the source, so a
        # database round trip can never change a value and an equality assertion on a reloaded run
        # cannot fail by microseconds.
        sa.Column("requested_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=True),
        # The three constraints are TR-2 and TR-5 where Python cannot reach: three domain methods do
        # not bind a hand-written UPDATE, a bad backfill or a `psql` session at 2 a.m. Each is an
        # equality between two predicates rather than an implication, which is what makes one
        # expression reject **both** bad pairings (AC-4's four in total, two per constraint).
        #
        # The first is written **once per document column, not against a conjunction**. The tempting
        # `(status = 'succeeded') = (tailored_cv IS NOT NULL AND cover_letter IS NOT NULL)` compares
        # a status against a conjunction, so a non-succeeded row holding exactly one of the two
        # documents satisfies it (`false = false`) — measured against a real database at T19, not
        # reasoned about. TR-5 is "a succeeded run has both documents; half a result is a failure",
        # and half a result in a row is exactly what the conjunction admits, so the expression was
        # strengthened and the spec amended to match. Take the authoritative text from
        # `infrastructure/persistence/mapping/tailoring/tailoring_run.py`, which is what ships.
        sa.CheckConstraint(
            "(status = 'succeeded') = (tailored_cv IS NOT NULL)"
            " AND (status = 'succeeded') = (cover_letter IS NOT NULL)",
            name=op.f("ck_tailoring_run_documents_match_status"),
        ),
        sa.CheckConstraint(
            "(status = 'failed') = (failure_reason IS NOT NULL)",
            name=op.f("ck_tailoring_run_failure_reason_matches_status"),
        ),
        # The two terminal statuses are exactly the two that carry a `completed_at`. `started_at`
        # gets **no** such constraint, deliberately: `mark_failed` is legal from `queued` (a refused
        # enqueue, G-14; a stale redelivery, G-25), so a failed run may legitimately never have
        # started, and a constraint tying the two would forbid a state the aggregate documents.
        sa.CheckConstraint(
            "(status IN ('succeeded','failed')) = (completed_at IS NOT NULL)",
            name=op.f("ck_tailoring_run_completed_at_matches_terminal_status"),
        ),
        # ON DELETE CASCADE is how this table joins ADR-0006's retention story without any retention
        # code in this slice: purging an expired session row deletes its runs in the same statement,
        # so the 1.6 purge needs no new predicate.
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["identity_guest_session.id"],
            name=op.f("fk_tailoring_run_guest_session_id_identity_guest_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tailoring_run")),
    )
    # One index, four readers: the `GET /api/tailoring-runs` list query, `count_for_session`,
    # `find_active_for_session`, and the cascade above. **No partial index on the active statuses** —
    # with at most twenty runs per session, this index plus a filter is free; a partial one is the
    # change to make if a session ever holds thousands of runs.
    op.create_index(
        op.f("ix_tailoring_run_guest_session_id"),
        "tailoring_run",
        ["guest_session_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_tailoring_run_guest_session_id"), table_name="tailoring_run")
    op.drop_table("tailoring_run")
