"""add role to identity user

Revision ID: 3d26e05edffe
Revises: b10d1c777b0a
Create Date: 2026-10-10 10:34:58.465794

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

Slice 4.1 (ADR-0032, technical plan §3 and §6): every registered user holds one role, `user` or
`admin`. One column on `identity_user` and one CHECK. The reasons for both are on the `Table` in
`infrastructure/persistence/mapping/identity/user.py`.

**Expand-only, and the default stays for good** (plan §0.8). `role VARCHAR(16) NOT NULL DEFAULT
'user'` is metadata-only on PostgreSQL 11+ (a constant default, no table rewrite), and it is what
keeps the previous image's registrations valid during the deploy window (R-27): that image INSERTs
without the column. There is no contract step.

**This revision and its mapping landed in one commit**, against plan §0.7's two. §0.7's argument
holds for writes: an unmapped insert gets `DEFAULT 'user'`, which satisfies
`ck_identity_user_role_known`. What it missed is the schema-drift guard: three migration tests
assert that autogenerate against head produces an empty diff, and with this revision alone the
database carries a column and a CHECK the metadata lacks, so they go red. Migration and mapping are
therefore one change (3.2's precedent, for a different reason).

**One revision, plain `ADD CONSTRAINT`.** The CHECK scans the table under `ACCESS EXCLUSIVE`, and
because Alembic runs a revision in one transaction the lock is held until the revision commits
(CLAUDE.md footgun: `NOT VALID` → `VALIDATE` inside one revision releases nothing). Production's
`identity_user` holds a handful of rows (AC-41(a) records the number), so that is milliseconds. It
is named here so nobody copies the pattern onto a large table: split the revision there.

**Downgrade refuses while any account holds a role other than `user`** — 2.2/2.3/3.1/3.2's stance
(refuse when a downgrade would make data mean something else). Dropping the column would silently
turn an administrator into an ordinary account with no record that it ever was one; the operator
revokes first, on purpose. On user-only data it drops the constraint, then the column (one
dropped-column slot, PR #12).

**Reviewed line by line.** The draft generated `add_column` with `server_default=sa.text("'user'")`
(the quotes are present: it renders `DEFAULT 'user'`, not the identifier `user`) and
`create_check_constraint(op.f('ck_identity_user_role_known'), …)`, and nothing else: no invented
drop. Its downgrade lacked the refusal, which is hand-written below in `b10d1c777b0a`'s shape.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op

revision: str = "3d26e05edffe"
down_revision: str | None = "b10d1c777b0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CHECK_NAME = "ck_identity_user_role_known"
_NON_USER_SQL = "FROM identity_user WHERE role <> 'user'"
_REFUSAL = "{count} account(s) hold the admin role; run revoke-role for each before downgrading."


def upgrade() -> None:
    # `RoleType.impl`. The default is quoted SQL: `'user'` the string, not `user` the identifier.
    op.add_column(
        "identity_user",
        sa.Column("role", sa.String(length=16), nullable=False, server_default=sa.text("'user'")),
    )
    op.create_check_constraint(op.f(_CHECK_NAME), "identity_user", "role IN ('user','admin')")


def downgrade() -> None:
    # Taken before the look, so no admin can be granted between the count and the `DROP COLUMN`
    # (which needs `ACCESS EXCLUSIVE` anyway).
    op.execute("LOCK TABLE identity_user IN ACCESS EXCLUSIVE MODE")
    if context.is_offline_mode():
        # A generated script has no connection to ask, so the refusal travels in the SQL itself.
        # Interpolates only this module's constants, none of which holds a quote.
        op.execute(
            f"DO $$ BEGIN IF EXISTS (SELECT 1 {_NON_USER_SQL}) "
            f"THEN RAISE EXCEPTION '{_REFUSAL.format(count='some')}'; END IF; END $$"
        )
    else:
        count = op.get_bind().execute(sa.text(f"SELECT count(*) {_NON_USER_SQL}")).scalar_one()
        if count:
            raise RuntimeError(_REFUSAL.format(count=count))

    op.drop_constraint(op.f(_CHECK_NAME), "identity_user", type_="check")
    op.drop_column("identity_user", "role")
