"""add job posting

Revision ID: 088f1ff1f00f
Revises: 3a39cf023a18
Create Date: 2026-09-09 21:13:36.455352

Autogenerated output is a DRAFT (ADR-0007). Before committing this file, check that it is:
  - additive and backward-compatible (expand -> migrate -> contract), because the deploy runs the
    old and new application versions at the same time for a few seconds;
  - free of drops it invented for indexes or constraints that exist in the database but not in the
    Table definition (autogenerate cannot see those, and will propose deleting them forever).

This revision is purely additive: one new table, one FK, one index, one check constraint, and
nothing existing is touched. Expand -> migrate -> contract is therefore trivially satisfied — the
previous application version simply never reads `posting_job_posting`, which is what makes the brief
two-version deploy window safe.

Hand-fixed after autogenerate, and **the same failure as the first revision, because nothing about
it was fixed at the source**: every `TypeDecorator` column (`JobPostingIdType`, `GuestSessionIdType`,
`PostingSourceType`, `SourceUrlType`, `PostingTitleType`, `JobPostingTextType`) came out as a bare
reference to the Python class —
`tailorcraft.infrastructure.persistence.types.posting.JobPostingIdType()` — with no `import
tailorcraft` anywhere in the file. That is not a rendering nicety to tidy up; the generated module
raises `NameError: name 'tailorcraft' is not defined` the moment Alembic `exec`s it, which is
exactly what running the draft produced before this rewrite.

Every such column below is rewritten to the `TypeDecorator`'s own `impl` — the column's actual wire
type in PostgreSQL — which is also the structurally right thing: a migration describes the *schema*,
not the ORM layer that happens to produce it today. If `SourceUrlType` were replaced tomorrow with a
different decorator over the same `VARCHAR(2048)`, this file should not change, and now it would not
have to.

`TIMESTAMP(timezone=True, precision=0)`, the CHECK, the FK and the index all came out of autogenerate
correct, because `job_posting_table` declares those directly rather than through a `TypeDecorator`.

Verified by hand: `alembic upgrade head` then `alembic downgrade -1` against a database at
3a39cf023a18, then `upgrade head` again.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "088f1ff1f00f"
down_revision: str | None = "3a39cf023a18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "posting_job_posting",
        # `JobPostingIdType.impl` — a native Postgres UUID.
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # `GuestSessionIdType.impl` — likewise.
        sa.Column("guest_session_id", postgresql.UUID(as_uuid=True), nullable=False),
        # `PostingSourceType.impl` — VARCHAR(16), deliberately not a native Postgres ENUM: adding a
        # member to one takes a lock. The CHECK below and the value object are the enforcement.
        sa.Column("source", sa.String(length=16), nullable=False),
        # `SourceUrlType.impl`. Nullable iff the posting was pasted (see the CHECK). PII.
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        # `PostingTitleType.impl`. Null for every pasted posting (J-4) and for a fetched page whose
        # metadata carried no usable title.
        sa.Column("title", sa.String(length=200), nullable=True),
        # `JobPostingTextType.impl` — TEXT, not a bounded VARCHAR: on PostgreSQL they are the same
        # storage and the same speed, and a length here would be a second home for the domain's
        # 30,000-character rule.
        sa.Column("text", sa.Text(), nullable=False),
        # Whole-second by contract (ADR-0007): the `Clock` port truncates at the source, so a
        # database round trip can never change a value and an equality assertion cannot fail by
        # microseconds.
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True, precision=0), nullable=False),
        # Invariant J-2 where Python cannot reach it. Rejects both bad pairings: a fetched row with
        # no URL, and a pasted row carrying one.
        sa.CheckConstraint(
            "(source = 'fetched') = (source_url IS NOT NULL)",
            name=op.f("ck_posting_job_posting_source_url_matches_source"),
        ),
        # ON DELETE CASCADE is how ADR-0006's retention promise reaches this table without any
        # retention code in this slice: deleting an expired session row deletes its postings in the
        # same statement, so the 1.6 purge needs no new predicate.
        sa.ForeignKeyConstraint(
            ["guest_session_id"],
            ["identity_guest_session.id"],
            name=op.f("fk_posting_job_posting_guest_session_id_identity_guest_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posting_job_posting")),
    )
    # Serves the list query, `count_for_session`, AND the cascade above. It exists before 1.6 needs
    # it, so the first purge run is not also the first sequential scan of a growing table.
    op.create_index(
        op.f("ix_posting_job_posting_guest_session_id"),
        "posting_job_posting",
        ["guest_session_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_posting_job_posting_guest_session_id"), table_name="posting_job_posting")
    op.drop_table("posting_job_posting")
